config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "posts#index"
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true, length: { maximum: 20 }
    validates :start_date, presence: true
    validates :end_date, presence: true
    validates :memo, length: { maximum: 500 }
    validate :start_end_check

    def start_end_check
        a = start_date ||1
        b = end_date ||1
        if a > b
            errors.add(:end_date, "は開始日より前の日付は登録できません")
        end
    end
end

app/models/user.rb
class User < ApplicationRecord
    validates :title, presence: true, length: { maximum: 20 }
    validates :start_date, presence: true
    validates :end_date, presence: true
    validates :memo, length: { maximum: 500 }
    validate :start_end_check

    def start_end_check
        a = start_date ||1
        b = end_date ||1
        if a > b
            errors.add(:end_date, "は開始日より前の日付は登録できません")
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(params.require(:post).permit(:title, :start_date, :end_date, :all_date, :memo))
    if @post.save
      flash[:notice] = "スケジュールを登録しました"
      redirect_to :posts
    else
      flash.now[:notice] = "スケジュールの登録に失敗しました"
      render "new"
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(params.require(:post).permit(:title, :start_date, :end_date, :all_date, :memo))
      flash[:notice] = "スケジュールを更新しました"
      redirect_to :posts
    else
      flash.now[:notice] = "スケジュールの更新に失敗しました"
      render "edit"
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = "予定を削除しました"
    redirect_to :posts
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params.require(:user).permit(:title, :start_date, :end_date, :all_date, :memo))
    if @user.save
      flash[:notice] = "スケジュールを登録しました"
      redirect_to :users
    else
      flash.now[:notice] = "スケジュールの登録に失敗しました"
      render "new"
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(params.require(:user).permit(:title, :start_date, :end_date, :all_date, :memo))
      flash[:notice] = "スケジュールを更新しました"
      redirect_to :users
    else
      flash.now[:notice] = "スケジュールの更新に失敗しました"
      render "edit"
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = "予定を削除しました"
    redirect_to :users
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Schedule</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h5>スケジュール管理アプリ</h5>
    </header>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<%= stylesheet_link_tag 'common', :media => "all" %>
<%= stylesheet_link_tag 'new', :media => "all" %>

<% if flash[:notice] %>
  <p class="notice"><%= flash[:notice] %></p>
<% end %>

<div class="container">
<h3>予定を編集してください</h3>
<%= render "shared/error", obj: @post %>

<div class="white">
<%= form_with model: @post,url: post_path, method: :patch do |f| %>
  <table>
    <tr>
      <th><%= f.label :title ,"タイトル" %></th>
      <td><%= f.text_field :title ,placeholder: "タイトル" %></td>
    </tr>

    <tr>
      <th><%= f.label :start_date ,"開始日" %></th>
      <td><%= f.date_field :start_date %></td>
    </tr>

    <tr>
      <th><%= f.label :end_date ,"終了日" %></th>
      <td><%= f.date_field :end_date %></td>
    </tr>

    <tr>
      <td class="no-block"><%= f.check_box :all_date , {}, "ture", "false" %></td>
      <th class="no-block"><%= f.label :all_date ,"終日の場合はチェックを入れます" %></th>
    </tr>

    <tr>
      <th><%= f.label :memo ,"スケジュールメモ" %></th>
      <td><%= f.text_area :memo ,placeholder: "メモを入力する" %></td>
    </tr>
  </table>

  <div>
    <ul class="left">
      <li><%= link_to "キャンセル", posts_path, class: "btn-white" %></li>
      <li><%= f.submit "保存", class: "btn" %></li>
    </ul>
  </div>
<% end %>
</div>
</div>

app/views/posts/index.html.erb
<%= stylesheet_link_tag 'common', :media => "all" %>
<%= stylesheet_link_tag 'index', :media => "all" %>

<body>
<div class="container">

<div>
<div class="between center">
<h3>予定一覧</h3>
<%= button_to "新規追加", :new_post, method: :get, class: "btn" %>
</div>

<% if flash[:notice] %>
   <p class="notice"><%= flash[:notice] %></p>
<% end %>

<div class="white">
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>タイトル</th>
      <th>開始日</th>
      <th>終了日</th>
      <th>終日</th>
      <th>更新日</th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.id %></td>
        <td><%= post.title %></td>
        <td><%= post.start_date.strftime("%Y/%m/%d") %></td>
        <td><%= post.end_date.strftime("%Y/%m/%d") %></td>
        <td><%= post.all_date ? '○' : '' %></td>
        <td><%= post.updated_at.to_s(:datetime_jp) %></td>
        <td>
        <%= link_to "詳細", post_path(post) %>
        </td>
        <td>
          <%= link_to "編集", edit_post_path(post) %>
        </td>
        <td>
          <%= link_to "削除", post_path(post), method: :delete, data: { confirm: "予定を削除しますか？" } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<div class="white under">
<p>予定合計<%= Post.count %>件</p>
<p class="thin">本日の日付<%= Date.today.strftime("%Y/%m/%d") %></p>
</div>

</div>
</div>
</body>

app/views/posts/new.html.erb
<%= stylesheet_link_tag 'common', :media => "all" %>
<%= stylesheet_link_tag 'new', :media => "all" %>

<% if flash[:notice] %>
  <p class="notice"><%= flash[:notice] %></p>
<% end %>

<div class="container">
  <h3>予定の新規追加</h3>
  <%= render "shared/error", obj: @post %>
  <div class="white">
    <%= form_with model: @post,url: posts_path do |f| %>
    <table>
      <tr>
        <th><%= f.label :title ,"タイトル" %></th>
        <td><%= f.text_field :title ,placeholder: "タイトル" %></td>
      </tr>
      
      <tr>
        <th><%= f.label :start_date ,"開始日" %></th>
        <td><%= f.date_field :start_date %></td>
      </tr>
      <tr>
        <th><%= f.label :end_date ,"終了日" %></th>
        <td><%= f.date_field :end_date %></td>
      </tr>
      </tr>

      <tr>
        <td class="no-block"><%= f.check_box :all_date , {}, "ture", "false" %></td>
        <th class="no-block"><%= f.label :all_date ,"終日の場合はチェックを入れます" %></th>
      </tr>

      <tr>
        <th><%= f.label :memo ,"スケジュールメモ" %></th>
        <td><%= f.text_area :memo ,placeholder: "メモを入力する" %></td>
      </tr>
    </table>

    <div>
      <ul class="left">
        <li><%= link_to "キャンセル", posts_path, class: "btn-white" %></li>
        <li><%= f.submit "保存", class: "btn" %></li>
      </ul>
    </div>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<%= stylesheet_link_tag 'common', :media => "all" %>
<%= stylesheet_link_tag 'show', :media => "all" %>

<div class="container">
<div class="wid">

<div>
  <ul>
    <li><%= link_to "← 一覧に戻る", posts_path %></li>
  </ul>
</div>

<div class="between center">
<h3><%= @post.title %></h3>
<%= button_to "編集", edit_post_path(@post), method: :get, class: "btn-blue" %>
</div>

<div class="white">
<table>
  <tr>
    <th>開始日</th>
    <td><%= @post.start_date.strftime("%Y/%m/%d") %></td>
  </tr>
  <tr>
    <th>終了日</th>
    <td><%= @post.end_date.strftime("%Y/%m/%d") %></td>
  </tr>
  <tr>
    <th>終日</th>
    <td><%= @post.all_date ? '○' : '' %></td>
  </tr>
  <tr>
    <th>スケジュールメモ</th>
    <td><%= @post.memo %></td>
  </tr>
</table>
</div>

</div>
</div>

app/views/schedules/edit.html.erb
<%= stylesheet_link_tag 'common', :media => "all" %>
<%= stylesheet_link_tag 'new', :media => "all" %>

<% if flash[:notice] %>
  <p class="notice"><%= flash[:notice] %></p>
<% end %>

<div class="container">
<h3>予定を編集してください</h3>
<%= render "shared/error", obj: @user %>

<div class="white">
<%= form_with model: @user,url: schedule_path, method: :patch do |f| %>
  <table>
    <tr>
      <th><%= f.label :title ,"タイトル" %></th>
      <td><%= f.text_field :title ,placeholder: "タイトル" %></td>
    </tr>

    <tr>
      <th><%= f.label :start_date ,"開始日" %></th>
      <td><%= f.datetime_field :start_date %></td>
    </tr>

    <tr>
      <th><%= f.label :end_date ,"終了日" %></th>
      <td><%= f.datetime_field :end_date %></td>
    </tr>

    <tr>
      <td class="no-block"><%= f.check_box :all_date , {}, "ture", "false" %></td>
      <th class="no-block"><%= f.label :all_date ,"終日の場合はチェックを入れます" %></th>
    </tr>

    <tr>
      <th><%= f.label :memo ,"スケジュールメモ" %></th>
      <td><%= f.text_area :memo ,placeholder: "メモを入力する" %></td>
    </tr>
  </table>

  <div>
    <ul class="left">
      <li><%= link_to "キャンセル", schedules_path, class: "btn-white" %></li>
      <li><%= f.submit "保存", class: "btn" %></li>
    </ul>
  </div>
<% end %>
</div>
</div>

app/views/schedules/index.html.erb
<%= stylesheet_link_tag 'common', :media => "all" %>
<%= stylesheet_link_tag 'index', :media => "all" %>

<body>
<div class="container">

<div>
<div class="between center">
<h3>予定一覧</h3>
<%= button_to "新規追加", :new_schedule, method: :get, class: "btn" %>
</div>

<% if flash[:notice] %>
   <p class="notice"><%= flash[:notice] %></p>
<% end %>

<div class="white">
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>タイトル</th>
      <th>開始日</th>
      <th>終了日</th>
      <th>終日</th>
      <th>更新日</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.title %></td>
        <td><%= user.start_date.strftime("%Y/%m/%d") %></td>
        <td><%= user.end_date.strftime("%Y/%m/%d") %></td>
        <td><%= user.all_date ? '○' : '' %></td>
        <td><%= user.updated_at.to_s(:datetime_jp) %></td>
        <td>
        <%= link_to "詳細", schedule_path(user) %>
        </td>
        <td>
          <%= link_to "編集", edit_schedule_path(user) %>
        </td>
        <td>
          <%= link_to "削除", schedule_path(user), method: :delete, data: { confirm: "予定を削除しますか？" } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<div class="white under">
<p>予定合計<%= User.count %>件</p>
<p class="thin">本日の日付<%= Date.today.strftime("%Y/%m/%d") %></p>
</div>

</div>
</div>
</body>

app/views/schedules/new.html.erb
<%= stylesheet_link_tag 'common', :media => "all" %>
<%= stylesheet_link_tag 'new', :media => "all" %>

<% if flash[:notice] %>
  <p class="notice"><%= flash[:notice] %></p>
<% end %>

<div class="container">
  <h3>予定の新規追加</h3>
  <%= render "shared/error", obj: @user %>
  <div class="white">
    <%= form_with model: @user,url: schedules_path do |f| %>
    <table>
      <tr>
        <th><%= f.label :title ,"タイトル" %></th>
        <td><%= f.text_field :title ,placeholder: "タイトル" %></td>
      </tr>
      
      <tr>
        <th><%= f.label :start_date ,"開始日" %></th>
        <td><%= f.datetime_field :start_date %></td>
      </tr>
      <tr>
        <th><%= f.label :end_date ,"終了日" %></th>
        <td><%= f.datetime_field :end_date %></td>
      </tr>
      </tr>

      <tr>
        <td class="no-block"><%= f.check_box :all_date , {}, "ture", "false" %></td>
        <th class="no-block"><%= f.label :all_date ,"終日の場合はチェックを入れます" %></th>
      </tr>

      <tr>
        <th><%= f.label :memo ,"スケジュールメモ" %></th>
        <td><%= f.text_area :memo ,placeholder: "メモを入力する" %></td>
      </tr>
    </table>

    <div>
      <ul class="left">
        <li><%= link_to "キャンセル", schedules_path, class: "btn-white" %></li>
        <li><%= f.submit "保存", class: "btn" %></li>
      </ul>
    </div>
    <% end %>
  </div>
</div>

app/views/schedules/show.html.erb
<%= stylesheet_link_tag 'common', :media => "all" %>
<%= stylesheet_link_tag 'show', :media => "all" %>

<div class="container">
<div class="wid">

<div>
  <ul>
    <li><%= link_to "← 一覧に戻る", schedules_path %></li>
  </ul>
</div>

<div class="between center">
<h3><%= @user.title %></h3>
<%= button_to "編集", edit_schedule_path(@user), method: :get, class: "btn-blue" %>
</div>

<div class="white">
<table>
  <tr>
    <th>開始日</th>
    <td><%= @user.start_date.strftime("%Y/%m/%d") %></td>
  </tr>
  <tr>
    <th>終了日</th>
    <td><%= @user.end_date.strftime("%Y/%m/%d") %></td>
  </tr>
  <tr>
    <th>終日</th>
    <td><%= @user.all_date ? '○' : '' %></td>
  </tr>
  <tr>
    <th>スケジュールメモ</th>
    <td><%= @user.memo %></td>
  </tr>
</table>
</div>

</div>
</div>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
  <% obj.errors.full_messages.each do |message| %>
    <ul>
      <li><%= message %></li>
    </ul>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<%= stylesheet_link_tag 'common', :media => "all" %>
<%= stylesheet_link_tag 'new', :media => "all" %>

<% if flash[:notice] %>
  <p class="notice"><%= flash[:notice] %></p>
<% end %>

<div class="container">
<h3>予定を編集してください</h3>
<%= render "shared/error", obj: @user %>

<div class="white">
<%= form_with model: @user do |f| %>
  <table>
    <tr>
      <th><%= f.label :title ,"タイトル" %></th>
      <td><%= f.text_field :title ,placeholder: "タイトル" %></td>
    </tr>

    <tr>
      <th><%= f.label :start_date ,"開始日" %></th>
      <td><%= f.datetime_field :start_date %></td>
    </tr>

    <tr>
      <th><%= f.label :end_date ,"終了日" %></th>
      <td><%= f.datetime_field :end_date %></td>
    </tr>

    <tr>
      <td class="no-block"><%= f.check_box :all_date , {}, "ture", "false" %></td>
      <th class="no-block"><%= f.label :all_date ,"終日の場合はチェックを入れます" %></th>
    </tr>

    <tr>
      <th><%= f.label :memo ,"スケジュールメモ" %></th>
      <td><%= f.text_area :memo ,placeholder: "メモを入力する" %></td>
    </tr>
  </table>

  <div>
    <ul class="left">
      <li><%= link_to "キャンセル", :users, class: "btn-white" %></li>
      <li><%= f.submit "保存", class: "btn" %></li>
    </ul>
  </div>
<% end %>
</div>
</div>

app/views/users/index.html.erb
<%= stylesheet_link_tag 'common', :media => "all" %>
<%= stylesheet_link_tag 'index', :media => "all" %>

<body>
<div class="container">

<div>
<div class="between center">
<h3>予定一覧</h3>
<%= button_to "新規追加", :new_user, method: :get, class: "btn" %>
</div>

<% if flash[:notice] %>
   <p class="notice"><%= flash[:notice] %></p>
<% end %>

<div class="white">
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>タイトル</th>
      <th>開始日</th>
      <th>終了日</th>
      <th>終日</th>
      <th>更新日</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.title %></td>
        <td><%= user.start_date.strftime("%Y/%m/%d") %></td>
        <td><%= user.end_date.strftime("%Y/%m/%d") %></td>
        <td><%= user.all_date ? '○' : '' %></td>
        <td><%= user.updated_at.to_s(:datetime_jp) %></td>
        <td>
        <%= link_to "詳細", user %>
        </td>
        <td>
          <%= link_to "編集", [:edit, user] %>
        </td>
        <td>
          <%= link_to "削除", user, method: :delete, data: { confirm: "予定を削除しますか？" } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<div class="white under">
<p>予定合計<%= User.count %>件</p>
<p class="thin">本日の日付<%= Date.today.strftime("%Y/%m/%d") %></p>
</div>

</div>
</div>
</body>

app/views/users/new.html.erb
<%= stylesheet_link_tag 'common', :media => "all" %>
<%= stylesheet_link_tag 'new', :media => "all" %>

<% if flash[:notice] %>
  <p class="notice"><%= flash[:notice] %></p>
<% end %>

<div class="container">
  <h3>予定の新規追加</h3>
  <%= render "shared/error", obj: @user %>
  <div class="white">
    <%= form_with model: @user do |f| %>
    <table>
      <tr>
        <th><%= f.label :title ,"タイトル" %></th>
        <td><%= f.text_field :title ,placeholder: "タイトル" %></td>
      </tr>
      
      <tr>
        <th><%= f.label :start_date ,"開始日" %></th>
        <td><%= f.datetime_field :start_date %></td>
      </tr>
      <tr>
        <th><%= f.label :end_date ,"終了日" %></th>
        <td><%= f.datetime_field :end_date %></td>
      </tr>
      </tr>

      <tr>
        <td class="no-block"><%= f.check_box :all_date , {}, "ture", "false" %></td>
        <th class="no-block"><%= f.label :all_date ,"終日の場合はチェックを入れます" %></th>
      </tr>

      <tr>
        <th><%= f.label :memo ,"スケジュールメモ" %></th>
        <td><%= f.text_area :memo ,placeholder: "メモを入力する" %></td>
      </tr>
    </table>

    <div>
      <ul class="left">
        <li><%= link_to "キャンセル", users_path, class: "btn-white" %></li>
        <li><%= f.submit "保存", class: "btn" %></li>
      </ul>
    </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= stylesheet_link_tag 'common', :media => "all" %>
<%= stylesheet_link_tag 'show', :media => "all" %>

<div class="container">
<div class="wid">

<div>
  <ul>
    <li><%= link_to "← 一覧に戻る", :users %></li>
  </ul>
</div>

<div class="between center">
<h3><%= @user.title %></h3>
<%= button_to "編集", edit_user_path(@user), method: :get, class: "btn-blue" %>
</div>

<div class="white">
<table>
  <tr>
    <th>開始日</th>
    <td><%= @user.start_date.strftime("%Y/%m/%d") %></td>
  </tr>
  <tr>
    <th>終了日</th>
    <td><%= @user.end_date.strftime("%Y/%m/%d") %></td>
  </tr>
  <tr>
    <th>終日</th>
    <td><%= @user.all_date ? '○' : '' %></td>
  </tr>
  <tr>
    <th>スケジュールメモ</th>
    <td><%= @user.memo %></td>
  </tr>
</table>
</div>

</div>
</div>